import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { api } from "../../api/client";
import { PageShell } from "../../components/PageShell";
import { openAccountLogin } from "../../components/Header";
import { DesignIcon } from "../../components/DesignIcon";
import { LoadingState } from "../../components/LoadingState";
import { usePageTitle } from "../../lib/pageTitle";
import type { ForecastPlanSummary } from "../../types";
import { useAuth } from "./authSession";

function faDigits(value: number) {
  return String(value).replace(/\d/g, (digit) => "۰۱۲۳۴۵۶۷۸۹"[Number(digit)]);
}

function accessLabel(plan: ForecastPlanSummary | undefined) {
  if (!plan) return "دسترسی پیش‌بینی پس از ورود فعال می‌شود";
  const futureDays = Math.max(0, plan.visible_days_from_yesterday - 1);
  if (futureDays === 0) return "دسترسی تا امروز";
  return `دسترسی تا ${faDigits(futureDays)} روز آینده`;
}

export function SubscriptionPlansPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const { isAuthenticated, session } = useAuth();
  const [plans, setPlans] = useState<ForecastPlanSummary[]>([]);
  const [status, setStatus] = useState<"loading" | "ready" | "error">(
    "loading",
  );
  const [message, setMessage] = useState("");
  usePageTitle(undefined, { title: "اشتراک هواچ | هواچ" });

  useEffect(() => {
    let mounted = true;
    api
      .plans()
      .then((payload) => {
        if (!mounted) return;
        setPlans(payload.plans);
        setStatus("ready");
      })
      .catch(() => {
        if (mounted) setStatus("error");
      });
    return () => {
      mounted = false;
    };
  }, []);

  // Subscription plans have one canonical public URL. This also cleans up
  // links generated by older clients that carried a forecast continuation.
  useEffect(() => {
    if (!location.search) return;
    navigate("/account/plans", { replace: true });
  }, [location.search, navigate]);

  const freePlan = useMemo(
    () => plans.find((plan) => plan.tier === "free") ?? plans[0],
    [plans],
  );
  const professionalPlan = useMemo(
    () =>
      plans.find(
        (plan) => plan.code === "professional" && plan.tier === "paid",
      ) ?? plans.find((plan) => plan.tier === "paid"),
    [plans],
  );
  function beginPurchase() {
    if (!isAuthenticated) {
      openAccountLogin(location.pathname);
      return;
    }
    setMessage("درگاه پرداخت به‌زودی فعال می‌شود.");
  }

  return (
    <PageShell className="subscription-page" back>
      <section className="catalog-hero" aria-labelledby="subscription-title">
        <h1 id="subscription-title">اشتراک هواچ</h1>
        <p>وضعیت دسترسی و طرح‌های هواچ</p>
      </section>
      {status === "loading" ? <LoadingState /> : null}
      {status === "error" ? (
        <section className="subscription-message card-surface" role="alert">
          بارگذاری طرح‌ها ناموفق بود. دوباره تلاش کن.
        </section>
      ) : null}
      {status === "ready" ? (
        <section className="subscription-grid" aria-label="طرح‌های اشتراک">
          <article className="plan-card free">
            <div className="plan-top">
              <DesignIcon name="subscription" />
              <span>
                {session?.plan?.tier === "free" ? "طرح فعلی" : "طرح رایگان"}
              </span>
            </div>
            <div className="plan-title">
              <h2>{freePlan?.title ?? "عضویت رایگان"}</h2>
              {session?.plan?.tier === "free" ? (
                <span className="plan-badge">فعال</span>
              ) : null}
            </div>
            <p className="subscription-plan-access">{accessLabel(freePlan)}</p>
          </article>
          <article className="plan-card paid future-plan">
            <div className="plan-top">
              <DesignIcon name="lock" />
            </div>
            <div className="plan-title">
              <h2>{professionalPlan?.title ?? "طرح حرفه‌ای"}</h2>
              <span
                className={`plan-badge ${session?.plan?.tier === "paid" ? "" : "soon"}`}
              >
                {session?.plan?.tier === "paid" ? "فعال" : "به‌زودی"}
              </span>
            </div>
            <p className="subscription-plan-access">
              {accessLabel(professionalPlan)}
            </p>
            <small>
              {professionalPlan?.duration_months
                ? `عضویت ${faDigits(professionalPlan.duration_months)}ماهه · `
                : ""}
              خرید اشتراک هنوز فعال نیست.
            </small>

            <button
              type="button"
              className="disabled-purchase"
              onClick={beginPurchase}
            >
              {isAuthenticated ? "خرید اشتراک" : "ورود برای خرید"}
            </button>
            {message ? (
              <p className="subscription-plan-message" role="status">
                {message}
              </p>
            ) : null}
          </article>
        </section>
      ) : null}
    </PageShell>
  );
}
