# Generated by Django 5.2.17 on 2026-08-26 17:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(spatial_index=False, srid=4326),
        ),
    ]
