# Generated by Django 5.2.17 on 2026-10-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_forecastplan_duration_and_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastaccesspolicy',
            name='display_day_count',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
