# Generated by Django — nullable cloud_cover_pct / uv_index for live provider gaps.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0003_live_forecast_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastrecord",
            name="cloud_cover_pct",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="forecastrecord",
            name="uv_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]

