# Generated by Django 5.2.17 — align the model default with the database state.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0005_legacy_route_relation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherpoint",
            name="climate",
            field=models.CharField(default="alpine", max_length=32),
        ),
    ]
