# Generated by Django 5.2 — persist ingest facts for cross-process metrics.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0007_live_daily_forecasts"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastsnapshot",
            name="duration_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forecastsnapshot",
            name="requested_point_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="forecastsnapshot",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]


